# KRY projekt 2 2020
# RSA
# Anton Firc (xfirca00)
default:
	g++ -std=c++11 -o kry kry.cpp kry.hpp KeyGenerator.cpp KeyGenerator.hpp CipherModule.cpp CipherModule.hpp RSABreaker.cpp RSABreaker.hpp -lgmp -lm