default:
	ghc src/plg-2-nka.hs src/PLGmodule.hs src/PLGtransform.hs src/NKAmodule.hs -o plg-2-nka
clean:
	rm plg-2-nka src/plg-2-nka.o src/plg-2-nka.hi src/PLGmodule.o src/PLGmodule.hi src/PLGtransform.o src/PLGtransform.hi src/NKAmodule.hi src/NKAmodule.o
